### ISSUE TITLE
Starting styling with absolute position

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#14]
Hi! First off, fantastic work on the new docs and website. It's all looks fantastic! I really appreciate and low the attention and detail you've put into this project. Congrats.

I'm just working on adding it to a project and noticed that the map gets embedded with absolute positioning out of the box. I was wondering why this was the case and if it makes more sense to start with some generalized sane defaults instead?

Lastly an example that uses Maplibre would be wonderful :-)

**Comment by KaiHuebner** [comment]
Hi Dave,
The only reason behind this setting was, so that the map always fills the parent container.
Does this causes problems in your project?

The only MapLibre examples so far are:
https://github.com/GIShub4/solid-map-gl#usage-with-maplibre
https://github.com/GIShub4/solid-map-gl/tree/main/examples/intro-maplibre

I will include some in the documentation page.
