### ISSUE TITLE
Unable to resolve dependencies with maplibre

### ISSUE THREAD

**Issue by shishkin** [GIShub4/solid-map-gl#27]
Running trying the maplibre example, both npm and yarn are unable to resolve dpendencies:

NPM:

```
❯ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vite-template-solid@0.0.0
npm ERR! Found: mapbox-gl@1.0.0
npm ERR! node_modules/mapbox-gl
npm ERR!   mapbox-gl@"npm:empty-npm-package@1.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mapbox-gl@"^2.10.0" from solid-map-gl@1.4.9
npm ERR! node_modules/solid-map-gl
npm ERR!   solid-map-gl@"^1.4.9" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Yarn 1:

```
...
warning " > solid-map-gl@1.4.9" has incorrect peer dependency "mapbox-gl@^2.10.0".
...
```

I've used [react-map-gl](https://github.com/visgl/react-map-gl/blob/master/package.json#L42) wrapper before which worked fine probably because it's less strict on version of mapbox.

**Comment by KaiHuebner** [comment]
Hi Sergey,

Can you please try it with the latest version?
I updated the peer dependency requirements.
________________________________
From: Sergey Shishkin ***@***.***>
Sent: Sunday, October 16, 2022 7:23:20 PM
To: GIShub4/solid-map-gl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GIShub4/solid-map-gl] Unable to resolve dependencies with maplibre (Issue #27)


Running trying the maplibre example, both npm and yarn are unable to resolve dpendencies:

NPM:

❯ npm i

npm ERR! code ERESOLVE

npm ERR! ERESOLVE unable to resolve dependency tree

npm ERR!

npm ERR! While resolving: ***@***.***

npm ERR! Found: ***@***.***

npm ERR! node_modules/mapbox-gl

npm ERR!   mapbox-gl@***@***.***" from the root project

npm ERR!

npm ERR! Could not resolve dependency:

npm ERR! peer mapbox-gl@"^2.10.0" from ***@***.***

npm ERR! node_modules/solid-map-gl

npm ERR!   solid-map-gl@"^1.4.9" from the root project

npm ERR!

npm ERR! Fix the upstream dependency conflict, or retry

npm ERR! this command with --force, or --legacy-peer-deps

npm ERR! to accept an incorrect (and potentially broken) dependency resolution.



Yarn 1:

...

warning " > ***@***.***" has incorrect peer dependency "mapbox-gl@^2.10.0".

...



I've used react-map-gl<https://github.com/visgl/react-map-gl/blob/master/package.json#L42> wrapper before which worked fine probably because it's less strict on version of mapbox.

**Comment by shishkin** [comment]
Thanks a lot @KaiHuebner for quick turn around. Latest version works!

Also appreciate you starting to track releases on GitHub!
