### ISSUE TITLE
Issues with map updates

### ISSUE THREAD

**Issue by infograafikko** [GIShub4/solid-map-gl#3]
Thank you for very nice tool. I noticed some bugs while testing. Sync Maps Demo (https://determined-mirzakhani-29bbc7.netlify.app/) doesn't seem to be working on Mac OS 11.6.4 (tested on Chrome and Safari). If I move one of the maps, other maps won't update viewport to same position.

Also I didn't manage to get ref prop working. 

```const App = () => {
  const [viewport, setViewport] = createSignal({
    center: [138.74, 35.3],
    zoom: 11,
    pitch: 70,
  } as Viewport);

  let mapRef;
  createEffect(() => console.log(mapRef))

  return (
    <MapGL
      options={{
        accessToken: MAPBOX_ACCESS_TOKEN,
        style: "mapbox://styles/mapbox/satellite-v9",
        attributionControl: false,
      }}
      viewport={viewport()}
      onViewportChange={(evt) => setViewport(evt)}
      ref={mapRef}
    >
      <Source
        source={{
          type: "raster-dem",
          url: "mapbox://mapbox.terrain-rgb",
          tileSize: 512,
          maxzoom: 14,
        }}
      >
      </Source>
    </MapGL>
  );
};
```

mapRef returns `undefined`

**Comment by col16** [comment]
I can confirm that the sync maps demo isn't working for me either.

**Comment by infograafikko** [comment]
@KaiHuebner Did you make any changes to playground? On windows sync maps seems to work now. I have to test independent app later.

I was trying to use `ref` prop to animate the scene. My idea was to circle camera around point of interest in 3d example.

**Comment by col16** [comment]
I was just about to try that code as an independent app, but the sync maps playground now works for me too (MacOS Safari)!

**Comment by KaiHuebner** [comment]
Hi guys,
Yes, I updated to the playground yesterday and added a couple more examples. I'm still not quite sure what is causing the issue. I think the SolidJS versions of the library and the playground were out of sync.

@infograafikko I done a fly around a point in one of my projects. I updated the viewport like this:
```
let rotateIndex = 0

const rotate = () => {
  setViewport(v => ({ ...v, bearing: (rotateIndex / 20) % 360, duration: 0 }))
  rotateIndex++
  requestAnimationFrame(rotate)
}
```
I'm thinking to add this functionality to the library, since it seems used very often.
I also look into the [FreeCamera API](https://docs.mapbox.com/mapbox-gl-js/api/properties/#freecameraoptions) which can do similar things. [Example](https://docs.mapbox.com/mapbox-gl-js/example/free-camera-point/)
