### ISSUE TITLE
Issues displaying

### ISSUE THREAD

**Issue by sachaw** [GIShub4/solid-map-gl#64]
by default the map container has a `z-index` of `-1`, this requires the parent element to have a higher z-index than 1.
To overcome this, I tried using the class prop (I'm using tailwind for styling). But if anything is supplied I the page spam creates new lines, overflowing the viewport and the map is never rendered.
it would be ideal id it acted like a normal div and would inherit it's parent's available space

**Comment by KaiHuebner** [comment]
Hi Sascha,
By default the map container has the following css properties:
```css
{
  position: 'absolute',
  inset: 0,
  'z-index': -1,
}
```
This is done so that the map fills the full page and every child div in `MapGL` component is  displayed on top of the map.

When you set the style or class property of the `MapGL` component these css properties are all removed and you can style it your way.
Please keep in mind that the underlying Mapbox map needs an explicit height value to display. Something like this:

```jsx
<div class='h-[50vh] w-[50vw]'>
  <MapGL
    class='h-full w-full' >
  ...
  </MapGL>
</div>
```
